# Generated by Django 3.2.18 on 2023-03-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='saving',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
